package com.skyface.taskmanager.kotlin.utils

import java.awt.Color

val COLOR_BLACK = Color(0x000000)
val COLOR_WHITE = Color(0xFFFFFF)

val COLOR_TRANSPARENT = Color(0x00000000, true)

val DEFAULT_BACKGROUND = Color(0x242F3D)

val BORDER_LINE_COLOR = Color(0x17212B)

val TOOLBAR_BACKGROUND = Color(0x0E1621)

val MINIMIZE_BUTTON_BACKGROUND_IDLE = Color(0x0E1621)
val MINIMIZE_BUTTON_FOREGROUND_IDLE = Color(0x576673)
val MINIMIZE_BUTTON_BACKGROUND_HOVER = Color(0x2C3847)
val MINIMIZE_BUTTON_FOREGROUND_HOVER = Color(0xFFFFFF)

val CLOSE_BUTTON_BACKGROUND_IDLE = Color(0x0E1621)
val CLOSE_BUTTON_FOREGROUND_IDLE = Color(0x576673)
val CLOSE_BUTTON_BACKGROUND_HOVER = Color(0xFF4F69)
val CLOSE_BUTTON_FOREGROUND_HOVER = Color(0xFFFFFF)

val DELETE_BUTTON_BACKGROUND_IDLE = Color(0x242F3D)
val DELETE_BUTTON_BACKGROUND_HOVER = Color(0xFF4F69)

val EDIT_BUTTON_BACKGROUND_IDLE = Color(0x242F3D)
val EDIT_BUTTON_BACKGROUND_HOVER = Color(0x5EB5F7)

val CREATE_BUTTON_BACKGROUND_IDLE = Color(0x242F3D)
val CREATE_BUTTON_BACKGROUND_HOVER = Color(0x32B432)

val TRAY_BACKGROUND = Color(0x242F3D)
val TRAY_ITEM_IDLE = Color(0x242F3D)
val TRAY_ITEM_HOVER = Color(0x2C3847)

val PICKER_BACKGROUND = Color(0x242F3D)
val PICKER_ITEM_SELECTION_BACKGROUND = Color(0x2C3847)
val PICKER_ITEM_SELECTION_FOREGROUND = Color(0xFFFFFF)

val DETAIL_BACKGROUND = Color(0x242F3D)

val EDIT_NAME_BACKGROUND = Color(0x242F3D)
val EDIT_DESCRIPTION_BACKGROUND = Color(0x242F3D)