package com.skyface.taskmanager.kotlin.utils

const val CONTAINER_WIDTH = 500
const val CONTAINER_HEIGHT = 600

const val TOOLBAR_WIDTH = CONTAINER_WIDTH
const val TOOLBAR_HEIGHT = 30


const val BUTTON_WIDTH = 180
const val BUTTON_HEIGHT = 40

const val PICKER_WIDTH = 200
const val PICKER_HEIGHT = CONTAINER_HEIGHT - TOOLBAR_HEIGHT - BUTTON_HEIGHT * 3 - 21

const val DETAIL_WIDTH = CONTAINER_WIDTH - PICKER_WIDTH
const val DETAIL_HEIGHT = CONTAINER_HEIGHT - TOOLBAR_HEIGHT

const val EDIT_NAME_WIDTH = DETAIL_WIDTH - 20
const val EDIT_NAME_HEIGHT = 45

const val EDIT_DESCRIPTION_WIDTH = DETAIL_WIDTH - 20
const val EDIT_DESCRIPTION_HEIGHT = 90

const val TRIGGER_PANEL_WIDTH = DETAIL_WIDTH - 20
const val TRIGGER_PANEL_HEIGHT = 80

const val DATE_PANEL_WIDTH = DETAIL_WIDTH - 20
const val DATE_PANEL_HEIGHT = 180

const val PATH_PANEL_WIDTH = DETAIL_WIDTH - 20
const val PATH_PANEL_HEIGHT = 70
